#!/usr/bin/env bash

set -e

bucket="${BUCKET:-gs://hilbert/colors}"

if [ $# -eq 0 ]; then
	"$0" "$(cat files)"
	exit 0
fi

for arg in "$@"; do
	remote="${arg#web/}"
	dest="$bucket/$remote"
	echo "Uploading: $remote"
	gsutil -h Cache-Control:private cp "$arg" "$dest" && gsutil acl ch -u AllUsers:R "$dest"
done
